### ISSUE TITLE
커뮤니티 로그인 시 글쓰기 완료 버튼 비작동

### ISSUE THREAD

**Issue by imtaejugkim** [kustaurant/Android#102]
### 버그에 대한 설명
- 커뮤니티 로그인 시 글쓰기 후, 완료 버튼 클릭 시 버튼 비작동

### 버그 수정을 위해 해야할 일
- 완료 시에 대한 처리

### 예상 작업 시간
- 2일 내외

**Comment by BeomBeom2** [comment]
완료했습니다.
